# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [4]:
print(np.__version__)
np.show_config(mode='stdout')


2.3.5
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Work/anaconda3/Library/include
    lib directory: C:/Users/Work/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Work/anaconda3/Library/include
    lib directory: C:/Users/Work/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  cython:
    commands: cython
    linker: cython
    name: cython
    vers

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [94]:
a = np.random.rand(2, 3, 5)
#a = np.random.randn(2, 3, 5)
#a = np.random.randint(1, 15, size =(2, 3, 5))



### 4. Print a.


In [95]:
print(a)


[[[0.42747741 0.14258915 0.82370093 0.30714017 0.14071785]
  [0.12885844 0.27427451 0.92986203 0.36050804 0.79523666]
  [0.46703767 0.07771482 0.2627967  0.17850088 0.23790422]]

 [[0.63280403 0.10663612 0.09197547 0.54338695 0.13545469]
  [0.70545854 0.95083496 0.01303971 0.18368528 0.02211303]
  [0.22100316 0.39603098 0.43779957 0.07028095 0.8761531 ]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [40]:
b = np.ones([5, 2, 3])



### 6. Print b.


In [41]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [39]:
np.size(a) == np.size(b)


True


### 8. Are you able to add a and b? Why or why not?


In [88]:
a_shape = np.shape(a)
b_shape = np.shape(b)

print(f"a: {a_shape}")
print(f"b: {b_shape}")

# Is not possible to add a and b because of mismatch of array shapes

a: (2, 3, 5)
b: (5, 2, 3)




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [89]:
c = np.transpose(b, (1, 2, 0))



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
d = np.add(a, c)

print(d)

# It works because both arrays have the same shape so NumPy can perform element-wise addition.


[[[1.88426396 1.37832327 1.20809695 1.93449449 1.02081325]
  [1.96204937 1.66892392 1.92697566 1.74685137 1.8007742 ]
  [1.9861857  1.70773641 1.73351443 1.80600186 1.9471125 ]]

 [[1.24373005 1.71041704 1.93910074 1.06195349 1.32793886]
  [1.63770247 1.34822559 1.96128665 1.14497877 1.94302712]
  [1.75103402 1.21855062 1.33090376 1.83145251 1.18594501]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
print(a)
print('##################################################################')
print(d)

# We added an array of ones (c) to array (a) which holds random values between 0 and 1. 
# They correspond element-wise in the same indices and have the difference of exactly 1. 

[[[0.88426396 0.37832327 0.20809695 0.93449449 0.02081325]
  [0.96204937 0.66892392 0.92697566 0.74685137 0.8007742 ]
  [0.9861857  0.70773641 0.73351443 0.80600186 0.9471125 ]]

 [[0.24373005 0.71041704 0.93910074 0.06195349 0.32793886]
  [0.63770247 0.34822559 0.96128665 0.14497877 0.94302712]
  [0.75103402 0.21855062 0.33090376 0.83145251 0.18594501]]]
##################################################################
[[[1.88426396 1.37832327 1.20809695 1.93449449 1.02081325]
  [1.96204937 1.66892392 1.92697566 1.74685137 1.8007742 ]
  [1.9861857  1.70773641 1.73351443 1.80600186 1.9471125 ]]

 [[1.24373005 1.71041704 1.93910074 1.06195349 1.32793886]
  [1.63770247 1.34822559 1.96128665 1.14497877 1.94302712]
  [1.75103402 1.21855062 1.33090376 1.83145251 1.18594501]]]



### 12. Multiply a and c. Assign the result to e.


In [96]:
e = np.multiply(a, c)




### 13. Does e equal to a? Why or why not?


In [98]:
np.array(a) == np.array(e)

# All elements in both arrays are element-wise equal.
# This is due to the multiplication of array (a) by array (c) (which contains only ones)
# keeps the elements inside of array (a) equal


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [99]:
d_min = np.min(d)
d_max = np.max(d)
d_mean = np.mean(d)



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [101]:
f = np.empty([2, 3, 5])

print(f)


[[[0.42747741 0.14258915 0.82370093 0.30714017 0.14071785]
  [0.12885844 0.27427451 0.92986203 0.36050804 0.79523666]
  [0.46703767 0.07771482 0.2627967  0.17850088 0.23790422]]

 [[0.63280403 0.10663612 0.09197547 0.54338695 0.13545469]
  [0.70545854 0.95083496 0.01303971 0.18368528 0.02211303]
  [0.22100316 0.39603098 0.43779957 0.07028095 0.8761531 ]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [ ]:
for index_0, block in enumerate(d):
    for index_1, row in enumerate(block):
        for index_2, scalar in enumerate(row):
            value = d[index_0, index_1, index_2]







### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [ ]:
print(d)
print('##########################')
print(f)


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [36]:
### [your code here]